# Jekyll Resume Theme

# Site settings
title: NCS27 Holdings
email: contact@ncs27.com
description: Solving problems on a massive scale using modern systems, innovative technologies, and a radical focus on reliability.
baseurl: ""
url: "http://ncs27.com"
name: NCS27 Holdings, Inc.
job: Solving problems on a massive scale using modern systems, innovative technologies, and a radical focus on reliability.
location: San Francisco, CA

# Build settings
markdown: kramdown
